# Generated by Django 5.0.1 on 2024-08-20 00:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, verbose_name='Renseigner la catégorie du produit')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('archive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeproduit', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('libelle', models.CharField(max_length=100, verbose_name='Désignation du produit')),
                ('quantite', models.IntegerField()),
                ('madein', models.CharField(blank=True, max_length=100, verbose_name='Pays de fabrication')),
                ('image1', models.ImageField(null=True, upload_to='produits/')),
                ('image2', models.ImageField(null=True, upload_to='produits/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('marque', models.CharField(max_length=100, null=True)),
                ('modele', models.CharField(max_length=100, null=True)),
                ('forme', models.CharField(max_length=100, null=True)),
                ('couleur', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('archive', models.BooleanField(default=False)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliation.categorieproduit')),
            ],
        ),
        migrations.CreateModel(
            name='PrixProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('archive', models.BooleanField(default=False)),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliation.produit')),
            ],
        ),
    ]
