# Generated by Django 5.0.1 on 2024-08-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0003_produit_description_alter_produit_couleur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prixproduit',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
