# Generated by Django 5.0.1 on 2024-08-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0006_alter_user_options_panier_articlepanier'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepanier',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='panier',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
