# Generated by Django 5.0.1 on 2024-08-22 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0007_articlepanier_archive_panier_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiquevente',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='historiquevente',
            name='quantite',
        ),
        migrations.AddField(
            model_name='historiquevente',
            name='panier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliation.articlepanier'),
        ),
    ]
