# Generated by Django 5.0.1 on 2024-08-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0008_remove_historiquevente_produit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiquevente',
            name='panier',
        ),
        migrations.AddField(
            model_name='historiquevente',
            name='panier',
            field=models.ManyToManyField(null=True, to='affiliation.articlepanier'),
        ),
    ]
