# Generated by Django 5.0.1 on 2024-08-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0009_remove_historiquevente_panier_historiquevente_panier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquevente',
            name='panier',
            field=models.ManyToManyField(to='affiliation.articlepanier'),
        ),
    ]
