# Generated by Django 5.0.1 on 2024-08-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0010_alter_historiquevente_panier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
