# Generated by Django 5.0.1 on 2024-08-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0011_user_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquevente',
            name='statut',
            field=models.CharField(blank=True, choices=[('Achevé', 'Achevé'), ('Traitement', 'Traitement'), ('En attente', 'En attente'), ('En cours', 'En cours')], max_length=120, null=True),
        ),
    ]
