# Generated by Django 5.0.1 on 2024-08-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0012_historiquevente_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquevente',
            name='commande',
            field=models.BooleanField(default=False),
        ),
    ]
