# Generated by Django 5.0.1 on 2024-08-23 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0013_historiquevente_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dix_milles',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pied_droit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pied_gauche',
        ),
        migrations.RemoveField(
            model_name='user',
            name='point_a_affecter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='point_fictive_col',
        ),
        migrations.RemoveField(
            model_name='user',
            name='point_fictive_inv',
        ),
        migrations.RemoveField(
            model_name='user',
            name='point_fictive_manag',
        ),
        migrations.RemoveField(
            model_name='user',
            name='poste',
        ),
        migrations.AlterField(
            model_name='user',
            name='nom_du_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Parrain'),
        ),
        migrations.CreateModel(
            name='GetPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveSmallIntegerField(default=0)),
                ('somme', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retrait', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parrainer', models.PositiveSmallIntegerField(default=0)),
                ('reinitialise', models.BooleanField(default=False)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliation.prixproduit')),
            ],
        ),
    ]
