# Generated by Django 5.0.1 on 2024-08-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0014_remove_user_dix_milles_remove_user_pied_droit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiquevente',
            options={'ordering': ('-id',)},
        ),
    ]
