# Generated by Django 5.0.1 on 2024-08-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0015_alter_historiquevente_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getpoint',
            name='somme',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='historiquevente',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='prixproduit',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
