# Generated by Django 5.0.1 on 2024-09-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0017_user_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palier',
            name='niveau',
        ),
        migrations.AddField(
            model_name='categorieproduit',
            name='points',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
