# Generated by Django 5.0.1 on 2024-09-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0018_remove_palier_niveau_categorieproduit_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorieproduit',
            name='points',
        ),
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='don_mand',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gam',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stock_point',
        ),
        migrations.AddField(
            model_name='categorieproduit',
            name='points_initial',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='categorieproduit',
            name='points_par_parrainage',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='categorieproduit',
            name='points_suivants',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='categorieproduit',
            name='seuil',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='balances',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='points_initial_attribues',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='categorieproduit',
            name='libelle',
            field=models.CharField(max_length=255, unique=True, verbose_name='Renseigner la catégorie du produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
    ]
