# Generated by Django 5.0.1 on 2024-09-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0019_remove_categorieproduit_points_remove_user_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balances',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='points_initial_attribues',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
