# Generated by Django 5.0.1 on 2024-09-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0022_payement'),
    ]

    operations = [
        migrations.AddField(
            model_name='prixproduit',
            name='ancien_prix',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
