# Generated by Django 5.0.1 on 2024-09-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0024_alter_prixproduit_ancien_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='payement',
            name='statut',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiquevente',
            name='statut',
            field=models.CharField(blank=True, choices=[('Achevé', 'Achevé'), ('En attente', 'En attente')], max_length=120, null=True),
        ),
    ]
