# Generated by Django 5.0.1 on 2024-09-25 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0026_alter_user_sexe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pays_de_residence',
            new_name='pays',
        ),
    ]
