# Generated by Django 5.0.1 on 2024-10-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0027_rename_pays_de_residence_user_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='don_bam',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='don_maya',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='don_zou',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='nb_pers_amene',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='palier_recommence',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
