# Generated by Django 5.0.1 on 2025-09-16 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0029_alter_payement_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KitArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliation.prixproduit')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliation.kitproduit')),
            ],
        ),
    ]
