# Generated by Django 5.0.1 on 2025-09-17 18:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0030_kitproduit_kitarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitarticle',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='kitarticle',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
