# Generated by Django 5.0.1 on 2025-09-18 13:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0031_kitarticle_prix_total_kitarticle_prix_unitaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitproduit',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
