# Generated by Django 5.0.1 on 2025-11-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0032_kitproduit_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='quantite',
            field=models.IntegerField(null=True),
        ),
    ]
