# Generated by Django 5.0.1 on 2025-11-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0033_alter_produit_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prixproduit',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
